---
- name: Replace the provided configuration with the existing running configuration
  hosts: nxos
  gather_facts: False
  collections:
    - cisco.nxos

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.nxos.nxos_vrf_global:
        config:
          vrfs:
            - name: temp
              description: Test
