---
- name: Replace the provided configuration with the existing running configuration
  hosts: nxos
  gather_facts: false
  collections:
    - cisco.nxos

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.nxos.nxos_vrf_global:
        config:
          vrfs:
            - name: temp
              description: Test
        state: merged
      register: vrf_output

    - name: Print VRF module output
      debug:
        var: vrf_output
